spring.application.name=demo-modulith-sb4


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.modulith.events.republish-outstanding-events-on-restart=true