apiVersion: v1
kind: Service
metadata:
  name: simple-test
  namespace: test
spec:
  selector:
    app: simple-test            # ← le Service route vers les pods portant ce label
  ports:
    - port: 80
      targetPort: 8080       # ← le port du conteneur